Trying to fix Caused by: java.lang.VerifyError: Bad type on operand stack
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[]
        at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45) ~[camel-api-3.5.0.jar!/:3.5.0]
        at org.apache.camel.support.DefaultExchange.setException(DefaultExchange.java:424) ~[camel-support-3.5.0.jar!/:3.5.0]
        at org.apache.camel.processor.TransformProcessor.process(TransformProcessor.java:78) ~[camel-base-3.5.0.jar!/:3.5.0]
        at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:404) [camel-base-3.5.0.jar!/:3.5.0]
        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148) [camel-base-3.5.0.jar!/:3.5.0]
        at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:60) [camel-base-3.5.0.jar!/:3.5.0]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:147) [camel-base-3.5.0.jar!/:3.5.0]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:287) [camel-base-3.5.0.jar!/:3.5.0]
        at org.apache.camel.component.seda.SedaConsumer.sendToConsumers(SedaConsumer.java:274) [camel-seda-3.5.0.jar!/:3.5.0]
        at org.apache.camel.component.seda.SedaConsumer.doRun(SedaConsumer.java:187) [camel-seda-3.5.0.jar!/:3.5.0]
        at org.apache.camel.component.seda.SedaConsumer.run(SedaConsumer.java:130) [camel-seda-3.5.0.jar!/:3.5.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/github/zobkov/webhook/GHPushToMimeMessage$_buildNewExcange_closure1.doCall(Ljava/lang/Object;)Ljava/lang/Object; @5: invokespecial
  Reason:
    Type 'com/github/zobkov/webhook/GHPushToMimeMessage$_buildNewExcange_closure1' (current frame, stack[2]) is not assignable to 'com/github/zobkov/webhook/GHPushToMimeMessage'
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'com/github/zobkov/webhook/GHPushToMimeMessage$_buildNewExcange_closure1', 'java/lang/Object' }
    stack: { uninitialized 0, uninitialized 0, 'com/github/zobkov/webhook/GHPushToMimeMessage$_buildNewExcange_closure1' }
  Bytecode:
    0x0000000: bb00 2559 2ab7 0028 4d2a b400 1ab6 002e
    0x0000010: 594e 2c2d 1230 b800 36c0 0030 b600 3a01
    0x0000020: 5757 2ab4 001c b600 2e59 3a04 2c19 0412
    0x0000030: 3cb8 0036 c000 3cb6 0040 0157 572c 593a
    0x0000040: 052a 1242 b900 4802 00c0 004a 1905 b900
    0x0000050: 4e02 0001 57b0 00bf
  Stackmap Table:
    full_frame(@86,{},{Object[#81]})

        at com.github.zobkov.webhook.GHPushToMimeMessage.buildNewExcange(GHPushToMimeMessage.groovy:45) ~[classes!/:?]
        at com.github.zobkov.webhook.GHPushToMimeMessage.evaluate(GHPushToMimeMessage.groovy:38) ~[classes!/:?]
        at com.github.zobkov.webhook.GHEventsDelegatingTranslator.evaluate(GHEventsDelegatingTranslator.groovy:28) ~[classes!/:?]
        at org.apache.camel.processor.TransformProcessor.process(TransformProcessor.java:47) ~[camel-base-3.5.0.jar!/:3.5.0]
        ... 11 more