Groovy seems has problems to set a property that actually represented by many overloaded methods.
Caused by: java.lang.IncompatibleClassChangeError: Class javax.mail.internet.MimeMessage does not implement the requested interface groovy.lang.GroovyObject
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setGroovyObjectProperty(ScriptBytecodeAdapter.java:544) ~[groovy-3.0.5.jar!/:3.0.5]
        at com.github.zobkov.webhook.AbstractGHEventToMimeMessage$_evaluate_closure1$_closure4.doCall(AbstractGHEventToMimeMessage.groovy:28) ~[classes!/:na]
        at com.github.zobkov.webhook.AbstractGHEventToMimeMessage$_evaluate_closure1$_closure4.call(AbstractGHEventToMimeMessage.groovy) ~[classes!/:na]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.with(DefaultGroovyMethods.java:351) ~[groovy-3.0.5.jar!/:3.0.5]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.tap(DefaultGroovyMethods.java:392) ~[groovy-3.0.5.jar!/:3.0.5]
        at com.github.zobkov.webhook.AbstractGHEventToMimeMessage$_evaluate_closure1.doCall(AbstractGHEventToMimeMessage.groovy:25) ~[classes!/:na]
        at com.github.zobkov.webhook.AbstractGHEventToMimeMessage$_evaluate_closure1.call(AbstractGHEventToMimeMessage.groovy) ~[classes!/:na]