Fix redelivery attempts when  javax.mail.MessagingException: Exception reading response  Caused by: java.net.SocketTimeoutException: Read timed out
2021-09-20 10:31:56,594 WARN  [Camel (camel-1) thread #0 - seda://email-sender] org.apache.camel.component.seda.SedaConsumer - Error processing exchange. Exchange[E3B7366A7FEC2A1-0000000000000054]. Caused by: [javax.mail.MessagingException - Exception reading response]
 javax.mail.MessagingException: Exception reading response
      at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2476) ~[jakarta.mail-1.6.7.jar:1.6.7]
      at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2172) ~[jakarta.mail-1.6.7.jar:1.6.7]
      at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722) ~[jakarta.mail-1.6.7.jar:1.6.7]
      at javax.mail.Service.connect(Service.java:342) ~[jakarta.mail-1.6.7.jar:1.6.7]
      at org.apache.camel.component.mail.DefaultJavaMailSender.send(DefaultJavaMailSender.java:153) ~[camel-mail-3.11.2.jar:3.11.2]
      at org.apache.camel.component.mail.MailProducer.process(MailProducer.java:71) ~[camel-mail-3.11.2.jar:3.11.2]
      at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:172) ~[camel-core-processor-3.11.2.jar:3.11.2]
      at org.apache.camel.management.DefaultInstrumentationProcessor.process(DefaultInstrumentationProcessor.java:90) ~[camel-management-3.11.2.jar:3.11.2]
      at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.doRun(RedeliveryErrorHandler.java:804) ~[camel-core-processor-3.11.2.jar:3.11.2]
      at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$RedeliveryTask.run(RedeliveryErrorHandler.java:712) ~[camel-core-processor-3.11.2.jar:3.11.2]
      at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:179) ~[camel-base-engine-3.11.2.jar:3.11.2]
      at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:64) ~[camel-base-engine-3.11.2.jar:3.11.2]
      at org.apache.camel.processor.Pipeline.process(Pipeline.java:184) ~[camel-core-processor-3.11.2.jar:3.11.2]
      at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:398) ~[camel-base-engine-3.11.2.jar:3.11.2]
      at org.apache.camel.component.seda.SedaConsumer.sendToConsumers(SedaConsumer.java:269) ~[camel-seda-3.11.2.jar:3.11.2]
      at org.apache.camel.component.seda.SedaConsumer.doRun(SedaConsumer.java:187) [camel-seda-3.11.2.jar:3.11.2]
      at org.apache.camel.component.seda.SedaConsumer.run(SedaConsumer.java:130) [camel-seda-3.11.2.jar:3.11.2]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_302]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_302]
      at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302]
 Caused by: java.net.SocketTimeoutException: Read timed out
      at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_302]
      at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_302]
      at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_302]
      at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_302]
      at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:102) ~[jakarta.mail-1.6.7.jar:1.6.7]
      at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_302]
      at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_302]
      at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:100) ~[jakarta.mail-1.6.7.jar:1.6.7]
      at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2456) ~[jakarta.mail-1.6.7.jar:1.6.7]
      ... 19 more